# brew tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "aws/tap"

# brew install
brew "aws-sam-cli"
brew "composer"
brew "curl"
brew "curl-openssl"
brew "git"
brew "go"
brew "golangci-lint"
brew "java"
brew "node"
brew "openssl"
brew "php"
brew "telnet"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"

# brew install --cask
cask "1password"
cask "1password-cli"
cask "brave-browser"
cask "discord"
cask "docker"
cask "fork"
cask "goland"
cask "phpstorm"
cask "insomnia"
cask "jetbrains-toolbox"
cask "postman"
cask "keka"
cask "mullvadvpn"
cask "qbittorrent"
cask "quicklook-json"
cask "slack"
cask "telegram"
cask "spotify"
cask "stats"
cask "tableplus"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
