#!/bin/bash

# Install zsh from main repo
sudo apt -y install zsh zsh-autosuggestions

# Install Powerlevel10k extension. Source: https://github.com/romkatv/powerlevel10k#installation
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

echo 'Now set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.'
