#!/bin/bash

# Source: https://mullvad.net/en/help/install-mullvad-app-linux/
wget --content-disposition https://mullvad.net/download/app/deb/latest
filename=$(ls | grep *.deb)
sudo apt install -y ./$filename
rm -rf ./$filename
