#!/bin/bash

# APT
sudo apt update && sudo apt -y install htop kodi lutris ntfs-3g openssl slack-desktop steam vlc telegram-desktop discord qbittorrent

# Flatpak
flatpak install --noninteractive io.dbeaver.DBeaverCommunity net.davidotek.pupgui2
