#!/bin/bash

# Source: https://docs.insomnia.rest/insomnia/install
echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" \
    | sudo tee -a /etc/apt/sources.list.d/insomnia.list
sudo apt update && sudo apt -y install insomnia
