#!/bin/bash

sudo add-apt-repository ppa:danielrichter2007/grub-customizer
sudo apt update && sudo apt -y install grub-efi grub2-common grub-customizer

echo 'Grub installed. Open grub-customizer to create and setup the boot page.'