#!/bin/bash

# Source: https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=linux&code=PCC
wget --content-disposition https://download.jetbrains.com/python/pycharm-community-2022.2.1.tar.gz
sudo tar xzf pycharm-*.tar.gz -C /opt/
rm -rf pycharm-*.tar.gz
echo '
You can find the PyCharm installation under /opt.
To create a desktop entry, do one of the following:
 - On the Welcome screen, click Configure | Create Desktop Entry
 - From the main menu, click Tools | Create Desktop Entry
'
