#!/bin/bash
sudo dnf -y install dnf-plugins-core
sudo dnf -y config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo usermod -aG docker $USER
# Start docker on boot
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
echo 'Docker installed. Reboot your system!'
