#!/bin/bash

# Source: https://www.jetbrains.com/go/download/download-thanks.html?platform=linux
wget --content-disposition https://download.jetbrains.com/go/goland-2022.2.2.tar.gz
sudo tar xzf goland-*.tar.gz -C /opt/
rm -rf goland-*.tar.gz
echo '
You can find the Goland installation under /opt.
To create a desktop entry, do one of the following:
 - On the Welcome screen, click Configure | Create Desktop Entry
 - From the main menu, click Tools | Create Desktop Entry
'
